## Lab 1: Data in Python

The data for this activity can be downloaded here (under "Data Sets"): https://www.statlearning.com/resources-python

As a first step, create a folder in this location called "data" and drop the Credit.csv file in that location.

If you open the ".gitignore" file, you'll notice that one of the entries is "data" so that your data files will not be shared on GitHub.

In [29]:
# !pip install pandas
# !pip install numpy

In [30]:
import pandas as pd
import numpy as np
Credit = pd.read_csv('data/Credit.csv')
Credit

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance
0,14.891,3606,283,2,34,11,No,No,Yes,South,333
1,106.025,6645,483,3,82,15,Yes,Yes,Yes,West,903
2,104.593,7075,514,4,71,11,No,No,No,West,580
3,148.924,9504,681,3,36,11,Yes,No,No,West,964
4,55.882,4897,357,2,68,16,No,No,Yes,South,331
...,...,...,...,...,...,...,...,...,...,...,...
395,12.096,4100,307,3,32,13,No,No,Yes,South,560
396,13.364,3838,296,5,65,17,No,No,No,East,480
397,57.872,4171,321,5,67,12,Yes,No,Yes,South,138
398,37.728,2525,192,1,44,13,No,No,Yes,South,0
399,18.701,5524,415,5,64,7,Yes,No,No,West,966

### What are the feature names?

Income, Limit, Rating, Cards, Age, Education, Own, Student, Married, Region, and Balance

### What are the data types of the feature values (i.e., numeric, categorical)

Income : Numeric, Limit : Numeric, Rating : Numeric, Cards : Numeric, Age : Numeric, Education : Numeric, Own: Binary, Student : Binary, Married: Binary, Region : Categorical, Balance : Numeric

### Find the mean, median, and mode of the feature "Age."

In [31]:
# mean 
Credit["Age"].mean()

np.float64(55.6675)

In [32]:
# median
Credit["Age"].median()

np.float64(56.0)

In [33]:
# mode
Credit["Age"].mode()

0    44
1    66
Name: Age, dtype: int64

### Create a subset of Credit that only contains the columns Age, Region, and Income. Call it "Subset."

In [34]:
Subset = Credit[["Age", "Region", "Income"]]
Subset

     Age Region   Income
0     34  South   14.891
1     82   West  106.025
2     71   West  104.593
3     36   West  148.924
4     68  South   55.882
..   ...    ...      ...
395   32  South   12.096
396   65   East   13.364
397   67  South   57.872
398   44  South   37.728
399   64   West   18.701

[400 rows x 3 columns]

### From this subset, create two partitions: 
- One that contains records for Ages below 50, and one that contains Ages 50+
- Call them "Younger" and "Older"

In [35]:
Younger = Credit[Credit["Age"]<50]
Younger

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance
0,14.891,3606,283,2,34,11,No,No,Yes,South,333
3,148.924,9504,681,3,36,11,Yes,No,No,West,964
6,20.996,3388,259,2,37,12,Yes,No,No,East,203
9,71.061,6819,491,3,41,19,Yes,Yes,Yes,East,1350
10,63.095,8117,589,4,30,14,No,No,Yes,South,1407
...,...,...,...,...,...,...,...,...,...,...,...
391,73.327,6555,472,2,43,15,Yes,No,No,South,721
392,25.974,2308,196,2,24,10,No,No,No,West,0
394,49.794,5758,410,4,40,8,No,No,No,South,734
395,12.096,4100,307,3,32,13,No,No,Yes,South,560
398,37.728,2525,192,1,44,13,No,No,Yes,South,0

In [36]:
Older = Credit[Credit["Age"]>=50]
Older

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance
1,106.025,6645,483,3,82,15,Yes,Yes,Yes,West,903
2,104.593,7075,514,4,71,11,No,No,No,West,580
4,55.882,4897,357,2,68,16,No,No,Yes,South,331
5,80.180,8047,569,4,77,10,No,No,No,South,1151
7,71.408,7114,512,2,87,9,No,No,No,West,872
...,...,...,...,...,...,...,...,...,...,...,...
390,135.118,10578,747,3,81,15,Yes,No,Yes,West,1393
393,17.316,1335,138,2,65,13,No,No,No,East,0
396,13.364,3838,296,5,65,17,No,No,No,East,480
397,57.872,4171,321,5,67,12,Yes,No,Yes,South,138
399,18.701,5524,415,5,64,7,Yes,No,No,West,966

### Use these partitions to compare the mean and median Income for each age group (less than 50 vs. 50+)

In [37]:
# mean of younger
Younger["Income"].mean()

np.float64(41.65203726708074)

In [38]:
# mean of older
Older["Income"].mean()

np.float64(47.6216569037657)

In [39]:
# median of younger
Younger["Income"].median()

np.float64(31.861)

In [40]:
# median of older
Older["Income"].median()

np.float64(33.694)

### What does the difference between mean and median suggest about the distribution of income?

It's skewed to the right, since the Mean is higher compared to the Median.

### What are the possible values for Region?

In [41]:
Credit["Region"].unique()

<StringArray>
['South', 'West', 'East']
Length: 3, dtype: str

### Use the value_counts method to build a frequency table for the possible values of Region.

In [42]:
Credit["Region"].value_counts()

Region
South    199
West     102
East      99
Name: count, dtype: int64

### Compare the average income for students vs. non-students.

In [47]:
Student = Credit[Credit["Student"]=="Yes"]
Student.head()

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance
1,106.025,6645,483,3,82,15,Yes,Yes,Yes,West,903
9,71.061,6819,491,3,41,19,Yes,Yes,Yes,East,1350
26,42.471,3625,289,6,44,12,Yes,Yes,No,South,654
35,23.350,2558,220,3,49,12,Yes,Yes,No,South,419
41,113.659,7659,538,2,66,15,No,Yes,Yes,East,1155

In [48]:
NonStudent = Credit[Credit["Student"]=="No"]
NonStudent.head()

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance
0,14.891,3606,283,2,34,11,No,No,Yes,South,333
2,104.593,7075,514,4,71,11,No,No,No,West,580
3,148.924,9504,681,3,36,11,Yes,No,No,West,964
4,55.882,4897,357,2,68,16,No,No,Yes,South,331
5,80.180,8047,569,4,77,10,No,No,No,South,1151

In [49]:
Student["Income"].mean()

np.float64(47.29205)

In [50]:
NonStudent["Income"].mean()

np.float64(44.988533333333336)

Students get paid more in general.

Often, banks will use a variable called _utilization_ to assess credit risk.
Utilization is the ratio of balance to limit (i.e., what % of the credit limit is being used?)
### Add a feature to the Credit dataset to measure utilization

In [55]:
Credit["Utilization"] = Credit["Balance"]/Credit["Limit"]
Credit

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance,Utilization
0,14.891,3606,283,2,34,11,No,No,Yes,South,333,0.092346
1,106.025,6645,483,3,82,15,Yes,Yes,Yes,West,903,0.135892
2,104.593,7075,514,4,71,11,No,No,No,West,580,0.081979
3,148.924,9504,681,3,36,11,Yes,No,No,West,964,0.101431
4,55.882,4897,357,2,68,16,No,No,Yes,South,331,0.067592
...,...,...,...,...,...,...,...,...,...,...,...,...
395,12.096,4100,307,3,32,13,No,No,Yes,South,560,0.136585
396,13.364,3838,296,5,65,17,No,No,No,East,480,0.125065
397,57.872,4171,321,5,67,12,Yes,No,Yes,South,138,0.033086
398,37.728,2525,192,1,44,13,No,No,Yes,South,0,0.000000
399,18.701,5524,415,5,64,7,Yes,No,No,West,966,0.174873

### What is the maximum utilization value in this set?

In [56]:
Credit["Utilization"].max()

np.float64(0.27693008426326576)